/* 
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef TALOS_DATA_CONFIG_HH
# define TALOS_DATA_CONFIG_HH

// Package version (header).
# define TALOS_DATA_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define TALOS_DATA_VERSION "1.2.2"
# define TALOS_DATA_MAJOR_VERSION 1
# define TALOS_DATA_MINOR_VERSION 2
# define TALOS_DATA_PATCH_VERSION 2

#define TALOS_DATA_VERSION_AT_LEAST(major, minor, patch) (TALOS_DATA_MAJOR_VERSION>major || (TALOS_DATA_MAJOR_VERSION>=major && \
                                                             (TALOS_DATA_MINOR_VERSION>minor || (TALOS_DATA_MINOR_VERSION>=minor && \
                                                                                                     TALOS_DATA_PATCH_VERSION>=patch))))

#define TALOS_DATA_VERSION_AT_MOST(major, minor, patch) (TALOS_DATA_MAJOR_VERSION<major || (TALOS_DATA_MAJOR_VERSION<=major && \
                                                            (TALOS_DATA_MINOR_VERSION<minor || (TALOS_DATA_MINOR_VERSION<=minor && \
                                                                                                     TALOS_DATA_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define TALOS_DATA_DLLIMPORT __declspec(dllimport)
#  define TALOS_DATA_DLLEXPORT __declspec(dllexport)
#  define TALOS_DATA_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define TALOS_DATA_DLLIMPORT __attribute__ ((visibility("default")))
#   define TALOS_DATA_DLLEXPORT __attribute__ ((visibility("default")))
#   define TALOS_DATA_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define TALOS_DATA_DLLIMPORT
#   define TALOS_DATA_DLLEXPORT
#   define TALOS_DATA_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef TALOS_DATA_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define TALOS_DATA_DLLAPI
#  define TALOS_DATA_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef talos_data_EXPORTS
#   define TALOS_DATA_DLLAPI TALOS_DATA_DLLEXPORT
#  else
#   define TALOS_DATA_DLLAPI TALOS_DATA_DLLIMPORT
#  endif // TALOS_DATA_EXPORTS
#  define TALOS_DATA_LOCAL TALOS_DATA_DLLLOCAL
# endif // TALOS_DATA_STATIC
#endif //! TALOS_DATA_CONFIG_HH
